# all services
services:
  - type: web
    name: svienna-remult-2023-06-19
    env: node
    repo: https://github.com/noam-honig/graphql-discussion-with-jycouet
    region: frankfurt
    plan: Free
    branch: ui/daisyui
    buildCommand: npm i -g pnpm; pnpm install --production=false; pnpm build
    startCommand: pnpm preview
    numInstances: 1
    #  healthCheckPath: /api/healthz
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
      - key: TZ
        value: utc
      - key: NODE_ENV
        value: production
      - key: AUTH_SECRET
        value: something-secret-to-change-for-prod
      - key: DATABASE_URL
        fromDatabase:
          name: svienna-remult-2023-06-19-db
          property: connectionString

# all databases
databases:
  - name: svienna-remult-2023-06-19-db
    databaseName: main_db
    region: frankfurt
    plan: Free
    postgresMajorVersion: 13
